# overwrite conf.d/10-ssl.conf
ssl_server_cert_file = /etc/letsencrypt/live/mail.cozmixng.org/fullchain.pem
ssl_server_key_file = /etc/letsencrypt/live/mail.cozmixng.org/privkey.pem

# overwrite conf.d/auth-passwdfile.conf
passdb passwd-file {
  #default_password_schema = CRYPT
  auth_username_format = %{user | username}
  passwd_file_path = /etc/dovecot/passwd
}

# overwrite conf.d/10-mail.conf
mail_driver = maildir
mail_path = ~/Maildir
mail_inbox_path = ~/Maildir

# overwrite conf.d/10-service.conf
service auth {
  # Postfix smtp-auth
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}
