- hosts: servers
  become: yes
  vars:
    ruby: ruby2.5
    ruby_api_version: 2.5.0
    passenger_version: 6.0.3
    slide_site_directory_relative: work/slide.rabbit-shocker.org
    slide_site_directory: ~rabbit-slide/work/slide.rabbit-shocker.org

  tasks:
    # Base
    - name: Upgrade packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: safe
    - name: Install base packages
      apt:
        name:
          - apt-listchanges
          - rsync
          - ruby
          - vim
    - name: Use VIM as the default editor
      command: update-alternatives --set editor /usr/bin/vim.basic
    - name: Use e-mail for apt-listchanges
      lineinfile:
        path: /etc/apt/listchanges.conf
        regexp: "^frontend="
        line: "frontend=mail"
    - name: Download keyring for Groonga APT repository
      get_url:
        url: https://packages.groonga.org/debian/groonga-archive-keyring.gpg
        dest: /usr/share/keyrings/groonga-archive-keyring.gpg
    - name: Install Groonga APT repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/groonga-archive-keyring.gpg] https://packages.groonga.org/debian/ buster main"
    - name: Install Bundler
      gem:
        name: bundler
        user_install: no

    # Let's Encrypt
    - name: Install certbot
      apt:
        name: certbot
    - name: "Put Let's Encrypt update script"
      copy:
        src: etc/letsencrypt/renewal-hooks/{{ item }}
        dest: /etc/letsencrypt/renewal-hooks/{{ item }}
        mode: 0700
      with_items:
        - post/start-apache2
        - post/start-dovecot
        - post/start-postfix
        - pre/stop-apache2
        - pre/stop-dovecot
        - pre/stop-postfix

    # Apache
    - name: Install Apache and related packages
      apt:
        name:
          - apache2
          - apache2-dev
          - build-essential
          - libapr1-dev
          - libaprutil1-dev
          - libcurl4-openssl-dev
          - libssl-dev
          - ruby-dev
          - zlib1g-dev
    - name: Set log rotation for Apache related logs
      lineinfile:
        path: /etc/logrotate.d/apache2
        regexp: "^	rotate"
        line: "	rotate 36500"
    - name: Install Passenger
      gem:
        name: passenger
        version: "{{ passenger_version }}"
        user_install: no
      register: passenger
    - name: Build Passenger
      command: passenger-install-apache2-module --languages ruby --auto
      when: passenger.changed
    - name: Put Passenger configuration files
      template:
        src: etc/apache2/mods-available/{{ item }}.j2
        dest: /etc/apache2/mods-available/{{ item }}
      with_items:
        - passenger.conf
        - passenger.load
      register: passenger_config_files
    - name: Enable Passenger
      command: a2enmod passenger
      when: passenger_config_files.changed
      notify:
        - Restart Apache
    - name: Disable Apache modules
      command: a2dismod {{ item }}
      with_items:
        - mpm_event
        - mpm_prefork
    - name: Enable Apache modules
      command: a2enmod {{ item }}
      with_items:
        - headers
        - mpm_worker
        - setenvif
        - ssl
      notify:
        - Restart Apache
    - name: Put Apache configuration file
      copy:
        src: etc/apache2/sites-available/{{ item }}
        dest: /etc/apache2/sites-available/{{ item }}
      with_items:
        - rabbit-shocker.org.conf
      register: apache_config_files
    - name: Enable our Apache configurations
      command: a2ensite {{ item }}
      with_items:
        - rabbit-shocker.org.conf
      notify:
        - Restart Apache
      when: apache_config_files.changed

    # slide.rabbit-shocker.org
    - name: Install slide.rabbit-shocker.org updater
      copy:
        src: lib/systemd/system/slide.rabbit-shocker.org.updater.{{ item }}
        dest: /lib/systemd/system/slide.rabbit-shocker.org.updater.{{ item }}
      with_items:
        - service
        - timer
      notify:
        - Restart slide.rabbit-shocker.org updater
    - name: Put email configuration for slide.rabbit-shocker.org webhook receiver
      copy:
        src: home/rabbit-slide/{{ slide_site_directory_relative }}/webhook-receiver/email.yaml
        dest: "{{ slide_site_directory }}/webhook-receiver/email.yaml"
        owner: rabbit-slide
        group: rabbit-slide
      notify:
        - Restart slide.rabbit-shocker.org webhook receiver
    - name: Create tmp/
      file:
        path: "{{ slide_site_directory }}/{{ item }}/tmp/"
        state: directory
        owner: rabbit-slide
        group: rabbit-slide
      with_items:
        - search
        - webhook-receiver
    - name: Remove Gemfile.lock
      file:
        path: "{{ slide_site_directory }}/{{ item }}/Gemfile.lock"
        state: absent
      with_items:
        - .
        - search
        - webhook-receiver
    - name: Update gems
      become_user: rabbit-slide
      shell: |
        bundle install --binstubs --path vendor/bundle
      args:
        chdir: "{{ slide_site_directory }}/{{ item }}/"
      with_items:
        - .
        - search
        - webhook-receiver
      notify:
        - Restart slide.rabbit-shocker.org searcher
        - Restart slide.rabbit-shocker.org webhook receiver
      vars:
        ansible_ssh_pipelining: true

    # Postfix
    - name: Install main.cf
      copy:
        src: etc/postfix/main.cf
        dest: /etc/postfix/main.cf
      notify:
        - Restart Postfix
    - name: Install transport_maps
      copy:
        src: etc/postfix/transport_maps
        dest: /etc/postfix/transport_maps
      register: postfix_transport_maps
    - name: Generate transport_maps.db
      shell: |
        postmap /etc/postfix/transport_maps
      when: postfix_transport_maps.changed
      notify:
        - Restart Postfix

  handlers:
    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted
    - name: Restart slide.rabbit-shocker.org updater
      systemd:
        name: slide.rabbit-shocker.org.updater.timer
        enabled: yes
        state: started
        daemon_reload: yes
    - name: Restart Postfix
      systemd:
        name: postfix
        state: restarted
    - name: Restart slide.rabbit-shocker.org searcher
      file:
        path: "{{ slide_site_directory }}/search/tmp/restart.txt"
        state: touch
        owner: rabbit-slide
        group: rabbit-slide
    - name: Restart slide.rabbit-shocker.org webhook receiver
      file:
        path: "{{ slide_site_directory }}/webhook-receiver/tmp/restart.txt"
        state: touch
        owner: rabbit-slide
        group: rabbit-slide
